# ---- Build Stage ----
FROM node:24-alpine AS builder
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci

COPY . .
RUN npm run build

# ---- Production Stage ----
FROM node:24-alpine AS runner
WORKDIR /app

COPY --from=builder /app/package.json      ./
COPY --from=builder /app/package-lock.json ./
COPY --from=builder /app/.next             ./.next
COPY --from=builder /app/node_modules      ./node_modules

EXPOSE 3000
CMD ["npm", "run", "start"]