# Build -------------------------------------------------------
FROM node:24-alpine AS builder

# Define o Diretório de Trabalho
WORKDIR /app

# Copia Dependências para o CONTÊINER
COPY package.json      ./
COPY package-lock.json ./

# Instala as Dependências com CLEAR INSTALL

# ci : Clear Install

RUN npm ci

# Copia RAIZ DO DIRETÓRIO para RAIZ DO CONTÊINER
COPY . .

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV API_URL=http://server:5000

# Executar BUILD
RUN npm run build

# Production --------------------------------------------------
FROM node:24-alpine AS runner
WORKDIR /app

# Copia Build para Contêiner
COPY --from=builder app/.next/standalone  ./
COPY --from=builder app/.next/static      ./.next/static

# Expõe Porta 3000
EXPOSE 3000

# Inicia a Aplicação
CMD ["node", "server.js"]