# ---- Build Stage ----
FROM node:24-alpine AS builder
WORKDIR /server

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ---- Production Stage ----
FROM node:24-alpine AS runner
WORKDIR /server

ENV HOST="127.0.0.1"
ENV PORT=5000
ENV ORIGIN="http://localhost:3000"

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /server/build ./build

EXPOSE 5000
CMD ["npm", "run", "start"]